CREATE DATABASE IF NOT EXISTS g3_workspace CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE g3_workspace;

CREATE TABLE IF NOT EXISTS kv_store (
  k VARCHAR(64) PRIMARY KEY,
  v LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
